### ISSUE TITLE
Not on PyPi

### ISSUE THREAD

**Issue by Chris-May** [UWKM/uwkm_streamfields#1]
The instructions mention pip installing this project. It appears as though it's not on PyPi.

`pip install uwkm_streamfields` yields:
```
Collecting uwkm_streamfields
  Could not find a version that satisfies the requirement uwkm_streamfields (from versions: )
No matching distribution found for uwkm_streamfields
```

**Comment by jellehermsen** [comment]
Thanks for noticing Chris. We switched the code to github and the PyPi package may have been deleted in the process. We'll add it again.

**Comment by StefanJilsink** [comment]
We have uploaded the project to PyPI. You may install the project via pip again.
